const primary_sidebar_links = [
 { name: "Dashboard", url: "/" },
 { name: "Product Category", url: "/product-category" },
 { name: "Contribution Community", url: "/contribution-community" },
 { name: "Discuss", url: "/discuss" },
 { name: "Challenges", url: "/challenges" },
 { name: "Jobs", url: "/jobs" },
 { name: "Internships", url: "/internships" },
 { name: "Resume", url: "/resume" },
 { name: "Recruiters", url: "/recruiters" },
 { name: "Projects", url: "/projects" },
 { name: "User Profiles", url: "/user-profiles" },
 { name: "Pro Subscriptions", url: "/pro-subscriptions" },
 { name: "Notifications", url: "/notifications" },
 { name: "Online Internships", url: "/online-internships" },
 { name: "Certifications", url: "/certifications" },
 { name: "Wallet", url: "/wallet" },
 { name: "Support Requests", url: "/support-requests" },
 { name: "Log History", url: "/log-history" },
 { name: "Vouchers", url: "/vouchers" },
 { name: "Panel Settings", url: "/panel-settings" },
];
export { primary_sidebar_links };
