import { formatNumber } from "../scripts/utils.js";

const primary_sidebar_links = [
 { name: "Dashboard", url: "/" },
 { name: "Product Category", url: "/product-category" },
 { name: "Contribution Community", url: "/contribution-community" },
 { name: "Discuss", url: "/discuss" },
 { name: "Challenges", url: "/challenges" },
 { name: "Jobs", url: "/jobs" },
 { name: "Internships", url: "/internships" },
 { name: "Resume", url: "/resume" },
 { name: "Recruiters", url: "/recruiters" },
 { name: "Projects", url: "/projects" },
 { name: "User Profiles", url: "/user-profiles" },
 { name: "Pro Subscriptions", url: "/pro-subscriptions" },
 { name: "Notifications", url: "/notifications" },
 { name: "Online Internships", url: "/online-internships" },
 { name: "Certifications", url: "/certifications" },
 { name: "Wallet", url: "/wallet" },
 { name: "Support Requests", url: "/support-requests" },
 { name: "Log History", url: "/log-history" },
 { name: "Vouchers", url: "/vouchers" },
 { name: "Panel Settings", url: "/panel-settings" },
];

const main_sidebar_links = [
 "Active Users",
 "New Sign-Up",
 "Courses",
 "Discuss",
 "Challenges",
 "Jobs",
 "Internships",
 "Projects",
 "My Profile",
 "Pro Benefits",
 "Notifications",
];

// Chart data with formatted hours
const chart_data = [
 { hours: formatNumber(1), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(2), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(3), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(4), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(5), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(6), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(7), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(8), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(9), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(10), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(11), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(12), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(13), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(14), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(15), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(16), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(17), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(18), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(19), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(20), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(21), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(22), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(23), users: Math.floor(Math.random() * 5000) },
 { hours: formatNumber(0), users: Math.floor(Math.random() * 5000) },
];
export { primary_sidebar_links, main_sidebar_links, chart_data };
